### ISSUE TITLE
some features

### ISSUE THREAD

**Issue by KimZing** [immuthex/redis-operator-doc#1]
> The following content comes from the machine translation, it may not be very smooth

I have tried almost all the Redis plug -in in the IDEA. At present, this plug -in is best to use. The operation of the actual project, if there is the following functions or optimization, I think it will be better.

1. When setting which databases are displayed,  can provide button to choose all database or ignore all database, so that can quickly select one or more databases. Because there are 200 databases in our company's Redis, it is troublesome to cancel one by one
2. Save the connection configuration of Redis in the .idea folder as a project settings, to synchronize the connection to the Git repository,  like the DataBase plugin of Jetbrains. Or set as a global connection like the DataBase plug -in

**Comment by immuthex** [comment]
Thank you for your advice!

1. Will be supported in the next release.
2. Do you mean that you need to support configuring Redis connection to project level and can synchronize to other computers via Git? Technically possible, but there are limitations: username and password are sensitive informations, which I am using [Persisting Sensitive Data](https://plugins.jetbrains.com/docs/intellij/persisting-sensitive-data.html) to store them, which means that this part of data will only be stored in the current OS and cannot be synchronized to other computers.

**Comment by KimZing** [comment]
Thanks for your reply.

    On the second point, when I create a connection using Datagrip, Datagrip saves the connection information in datasource.xml in the.idea folder, which contains the group name, connection name, commen, driver info, etc. and then  I will initialize the project as a git repository and synchronize it to the remote repository. When I use another computer, I just need to pull the repository and re-enter the password to use the connection.

     In this plug-in,  will use a similar storage process? For example, save the redis connection information in the redis-operator.xml file

**Comment by KimZing** [comment]
> Thank you for your advice!
> 
> 1. Will be supported in the next release.
> 2. Do you mean that you need to support configuring Redis connection to project level and can synchronize to other computers via Git? Technically possible, but there are limitations: username and password are sensitive informations, which I am using [Persisting Sensitive Data](https://plugins.jetbrains.com/docs/intellij/persisting-sensitive-data.html) to store them, which means that this part of data will only be stored in the current OS and cannot be synchronized to other computers.

Thanks for your reply.

On the second point, when I create a connection using Datagrip, Datagrip saves the connection information in datasource.xml in the.idea folder, which contains the group name, connection name, comment, driver info, etc. and then  I will initialize the project as a git repository and synchronize it to the remote repository. When I use another computer, I just need to pull the repository and re-enter the password to use the connection.

In this plug-in,  will use a similar storage process? For example, save the redis connection information in the redis-operator.xml file

**Comment by immuthex** [comment]
@KimZing The project-level Redis connection will be supported, and the file will saved in the project’s `.idea` folder, but the Redis username and password, SSH tunnel username and password will not be saved in the file, so you will need to re-enter the username and password on other computers.

What do you think of this?

**Comment by KimZing** [comment]
> @KimZing The project-level Redis connection will be supported, and the file will saved in the project’s `.idea` folder, but the Redis username and password, SSH tunnel username and password will not be saved in the file, so you will need to re-enter the username and password on other computers.
> 
> What do you think of this?

@immuthex yes, that is what i mean，Would you have any plans to support in the future?

**Comment by immuthex** [comment]
@KimZing Will supported it in the next release.

**Comment by immuthex** [comment]
@KimZing Version 2022.1.10 was released, I'm closing this one, we can reopen it if there are any issues. Thank you!
