### ISSUE TITLE
add comment field when create new connection

### ISSUE THREAD

**Issue by KimZing** [immuthex/redis-operator-doc#2]
> Machine translation

Hi ,  Could  add the comment field on the connection creation window and persist comment field in project-level xml files?   many people hope that  add some information use the comment filed.

like the  below
Name:           xxx
Comment:    xxx
Mode:           Standalone
Address:      localhost:6379

**Comment by immuthex** [comment]
@KimZing The comment field will be added in version 2022.1.11
