### ISSUE TITLE
add "scan all" feature

### ISSUE THREAD

**Issue by KimZing** [immuthex/redis-operator-doc#3]
Machine translation:
When I query a Key, such as ab*, and there is one million data in the database, I can only click scan more every time. Even if I set the number of scans each time, it is troublesome

**Comment by immuthex** [comment]
@KimZing I don't think the `scan all` feature is needed, because loading too many keys at once will have performance issues. You can configure `Scan count` to load more keys at once.
What do you think?

**Comment by KimZing** [comment]
@immuthex Maybe what you said is more appropriate， it is not a required feature，thanks for reply
